name: flutter_earth_globe
description: "An interactive and fully customizable 3D Globe widget written in pure Dart."
version: 2.2.0
homepage: https://github.com/Pana-g/flutter_earth_globe
repository: https://github.com/Pana-g/flutter_earth_globe

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  vector_math: ^2.1.4
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  shaders:
    - shaders/sphere.frag
    - shaders/background.frag

screenshots:
  - description: 'Flutter Earth Globe Sphere Day view'
    path: screenshots/screenshotEarthDay.png