name: Deploy App to GitHub Pages

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Build and Deploy ðŸš€
      uses: bluefireteam/flutter-gh-pages@v9
      with:
        baseHref: /flutter_earth_globe/
        targetBranch: gh-pages
        webRenderer: canvaskit
        workingDir: example
